services:
  web:
    container_name: flask
    hostname: flask
    build:
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    restart: always
  db:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    restart: always
